// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "mcp.server.enabled": boolean;
      "mcp.server.port": number;
      "mcp.server.allowRemote": boolean;
      "mcp.server.authToken": string;
      "mcp.server.requireAuth": boolean;
      "write.enabled": boolean;
      "write.confirmBeforeMutation": boolean;
      "write.allowFileImport": boolean;
      "privacy.exposeFilePaths": boolean;
      "hybrid.maxDocuments": number;
      "hybrid.maxChunksPerItem": number;
      "hybrid.keywordMinScore": string;
      "hybrid.semanticMinScore": string;
      "hybrid.keywordRrfWeight": string;
      "hybrid.semanticRrfWeight": string;
      "hybrid.minScore": string;
      "hybrid.thresholdSplitMigrated": boolean;
      "hybrid.chunkTargetChars": number;
      "hybrid.chunkAppendToleranceChars": number;
      "hybrid.neighborRadius": number;
      "hybrid.searchTimeoutMs": number;
      "hybrid.keywordSearchTimeoutMs": number;
      "hybrid.gpuAccelerationEnabled": boolean;
      "hybrid.gpuPrecision": string;
      "wiki.enabled": boolean;
      "wiki.autoWrite": boolean;
      "wiki.writeMode": string;
      "wiki.shadowMode": boolean;
      "wiki.minScore": string;
      "wiki.rrfWeight": string;
      "wiki.searchTimeoutMs": number;
      "semantic.enabled": boolean;
      "semantic.autoUpdate": boolean;
      "embedding.apiBase": string;
      "embedding.apiKey": string;
      "embedding.allowInsecureHTTP": boolean;
      "embedding.timeoutSeconds": number;
      "embedding.maxBatchItems": number;
      "mineru.enabled": boolean;
      "mineru.mode": string;
      "mineru.baseURL": string;
      "mineru.apiToken": string;
      "mineru.modelVersion": string;
      "mineru.language": string;
      "mineru.enableOCR": boolean;
      "mineru.enableFormula": boolean;
      "mineru.enableTable": boolean;
      "mineru.timeoutSeconds": number;
      "mineru.maxFileSizeMB": number;
      "mineru.concurrency": number;
      "mineru.blockingOnDemand": boolean;
      "mineru.attachMarkdown": boolean;
      "llm.provider": string;
      "llm.baseURL": string;
      "llm.apiKey": string;
      "llm.model": string;
      "llm.targetLanguage": string;
      "llm.systemPrompt": string;
      "translation.contextEnabled": boolean;
      "translation.expertMode": string;
      "translation.expertCustom": string;
      "translation.autoDocumentGlossary": boolean;
      "translation.useGlobalGlossary": boolean;
      "translation.globalGlossary": string;
      "translation.batchSize": number;
      "translation.concurrency": number;
      "translation.maxRetries": number;
    };
  }
}
