'use strict';
const fs=require('fs'), path=require('path'), vm=require('vm'), assert=require('assert/strict');
const root=path.resolve(process.env.XPI_SOURCE || path.join(__dirname,'../new'));
const source=fs.readFileSync(path.join(root,'content/scripts/zotero-lit-synapse.js'),'utf8');
const checks=[];
const resultsRoot=path.resolve(process.env.AUDIT_RESULTS || path.join(__dirname,'../results'));fs.mkdirSync(resultsRoot,{recursive:true});
async function check(name,fn,bug=false){if(process.env.AUDIT_FILTER&&!name.includes(process.env.AUDIT_FILTER))return;try{const details=await fn();checks.push({name,status:bug?'BUG_REPRODUCED':'PASS',details:details??null});}catch(e){checks.push({name,status:'FAIL',error:e.stack||String(e)});}}
function section(start,end){const a=source.indexOf('  // '+start),b=end?source.indexOf('  // '+end,a+1):source.indexOf('\n  // ',a+4);if(a<0||b<0)throw Error('Missing section '+start);return source.slice(a,b);}
function context(extra={}){const c={console,TextEncoder,TextDecoder,Uint8Array,AbortController,URL,URLSearchParams,setTimeout,clearTimeout,setInterval,clearInterval,atob,btoa,
 __esm:o=>{let done=false;return()=>{if(!done){done=true;return Object.values(o)[0]();}};},__export:(o,d)=>{for(const[k,v]of Object.entries(d))Object.defineProperty(o,k,{get:v});},ztoolkit:{log(){}},Zotero:{debug(){},logError(){}},...extra};for(const n of new Set(source.match(/\binit_\w+(?=\()/g)))c[n]=()=>{};return vm.createContext(c);}
function run(c,s){return vm.runInContext(s,c,{timeout:5000});}
const ticks=async(n=4)=>{for(let i=0;i<n;i++)await new Promise(r=>setImmediate(r));};
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};}
function memoryIO(){const disk=new Map(),dirs=new Set(),stats=new Map();return {disk,dirs,stats,io:{
 makeDirectory:async p=>{dirs.add(p);},exists:async p=>disk.has(p)||dirs.has(p),
 readUTF8:async p=>{if(!disk.has(p))throw Error('ENOENT '+p);return disk.get(p);},
 writeUTF8:async(p,s)=>{disk.set(p,s);},move:async(a,b)=>{if(!disk.has(a))throw Error('ENOENT '+a);disk.set(b,disk.get(a));disk.delete(a);},
 remove:async(p,o={})=>{disk.delete(p);dirs.delete(p);if(o.recursive){for(const k of disk.keys())if(k.startsWith(p+'/'))disk.delete(k);for(const k of dirs)if(k.startsWith(p+'/'))dirs.delete(k);}},
 stat:async p=>{if(stats.has(p))return stats.get(p);if(disk.has(p))return{size:Buffer.byteLength(disk.get(p)),lastModified:1000};throw Error('ENOENT '+p);},
 getChildren:async p=>[...new Set([...disk.keys(),...dirs])].filter(k=>path.posix.dirname(k)===p)
 }};}
function serverFixture(){const sockets=[],pending=[];let failInit=false;const c=context({
 Cc:{'@mozilla.org/network/server-socket;1':{createInstance(){const s={closed:false,closeCalls:0,init(p){if(failInit)throw Error('bind failed');this.port=p;},asyncListen(l){this.listener=l;},close(){this.closeCalls++;this.closed=true;if(this.listener)pending.push(()=>this.listener.onStopListening(this,0));}};sockets.push(s);return s;}}},
 Ci:{nsIServerSocket:{}},serverPreferences:{isRemoteAccessAllowed:()=>false},StreamableMCPServer:class{}
 });run(c,section('src/modules/httpServer.ts\n  var REQUEST_IDLE_TIMEOUT_MS','src/utils/locale.ts'));return {s:new c.HttpServer(),sockets,pending,fail:v=>failInit=v,flush:()=>pending.splice(0).forEach(f=>f())};}
function readerFixture(){const io=memoryIO();let owners=[];const c=context({process:{env:{ZMR_TEST:'1'}},PathUtils:{join:path.posix.join},IOUtils:io.io,Zotero:{debug(){},logError(){},DataDirectory:{dir:'/test-data'},getMainWindow:()=>({setTimeout,clearTimeout,AbortController}),Prefs:{get(){}},DB:{queryAsync:async()=>owners}}});let text=fs.readFileSync(path.join(root,'mark-reader/content/scripts/zotero-mark-reader.js'),'utf8');text=text.replace('  const testExports =','  globalThis.auditReader={state,getAttachmentDataDir,loadTranslationCache,saveTranslationCache,emptyTranslationCache,attachmentIdentity,loadLegacyTranslationCache};\n  const testExports =');run(c,text);return{...io,c,r:c.auditReader,t:c.ZoteroMarkReader.__test,setOwners:v=>owners=v};}
function hookFixture(){let timerID=0,observer,enabled=true;const timers=new Map(),builds=[],items=new Map();const service={isReady:async()=>true,isBuildActive:()=>false,getStats:async()=>({indexProgress:{status:'idle'}}),buildIndex:async o=>{builds.push(o);return{processed:0,total:0,status:'completed'};}};const c=context({
 setTimeout:(f,ms)=>{const id=++timerID;timers.set(id,{f,ms});return id;},clearTimeout:id=>timers.delete(id),setInterval:()=>++timerID,clearInterval(){},refreshSemanticColumn(){},SERVER_LISTENER_PREFS:{},
 semantic_exports:{getSemanticSearchService:()=>service},
 Zotero:{debug(){},logError(){},Prefs:{get:()=>enabled},Items:{get:ids=>ids.map(id=>items.get(id))},Libraries:{userLibraryID:1},Notifier:{registerObserver:o=>{observer=o;return 1;}}}
 });run(c,section('src/modules/libraryScope.ts'));const a=source.indexOf('  // src/hooks.ts\n  var PREF_SEMANTIC_AUTO_UPDATE');run(c,source.slice(a,source.indexOf('\n  // src/addon.ts',a)));c.registerItemNotifier();return{c,timers,builds,items,service,setEnabled:v=>enabled=v,notify:(...args)=>observer.notify(...args),async runImmediate(){const row=[...timers].find(([,v])=>v.ms===0);if(!row)return false;timers.delete(row[0]);await row[1].f();await ticks();return true;}};}
function regular(id,key,libraryID){return{id,key,libraryID,deleted:false,isRegularItem:()=>true,isAnnotation:()=>false,getField:()=>key};}
function minerFixture(){const io=memoryIO(),items=new Map(),imports=[],parseCalls=[];let seq=0,parseImpl;
 const parents=[{id:11,key:'PARENT01',libraryID:1,children:[],getAttachments(){return this.children;},getNotes:()=>[]},{id:77,key:'PARENT07',libraryID:7,children:[],getAttachments(){return this.children;},getNotes:()=>[]}];for(const p of parents)items.set(p.id,p);
 const c=context({PathUtils:{join:path.posix.join,parent:path.posix.dirname},IOUtils:io.io,Zotero:{debug(){},logError(){},DataDirectory:{dir:'/test-data'},Prefs:{get(){}},Libraries:{userLibraryID:1},
 Items:{getAsync:async id=>items.get(id),getByLibraryAndKeyAsync:async(lib,key)=>[...items.values()].find(v=>v.libraryID===lib&&v.key===key)},
 Attachments:{importFromFile:async o=>{const parent=items.get(o.parentItemID),id=1000+(++seq),key='MD'+String(seq).padStart(6,'0'),p='/storage/'+key+'/full.md';io.disk.set(p,io.disk.get(o.file));const item={id,key,libraryID:parent.libraryID,parentItemID:parent.id,dateModified:'2026-09-05 12:00:00',attachmentContentType:'text/markdown',isAttachment:()=>true,getField:()=>o.title,getFilePathAsync:async()=>p,eraseTx:async()=>{items.delete(id);parent.children=parent.children.filter(i=>i!==id);}};items.set(id,item);parent.children.push(id);imports.push({libraryID:parent.libraryID,parentItemID:parent.id,markdown:io.disk.get(p)});return item;}}
 }});
 run(c,section('src/modules/mineru/structuredDocumentAssembler.ts'));run(c,section('src/modules/mineru/minerUClient.ts'));run(c,section('src/modules/mineru/minerUService.ts'));run(c,'init_minerUService();');
 c.MinerUClient=class{async parseLocalFile(filePath){parseCalls.push(filePath);return await parseImpl(filePath);}};
 function result(text){const files={'content_list.json':JSON.stringify([{type:'text',text,page_idx:0,bbox:[0,0,100,100]}])};return{files,structuredSource:c.selectStructuredSource(files)};}
 parseImpl=async p=>result(p==='/pdf/a.pdf'?'Paper A evidence text.':'Paper B different evidence text.');
 const a={id:101,key:'SAMEKEY1',libraryID:1,parentItemID:11,attachmentFilename:'paper-a.pdf',isPDFAttachment:()=>true,getFilePathAsync:async()=>'/pdf/a.pdf',getField:()=> 'Paper A original'},b={id:107,key:'SAMEKEY1',libraryID:7,parentItemID:77,attachmentFilename:'paper-b.pdf',isPDFAttachment:()=>true,getFilePathAsync:async()=>'/pdf/b.pdf',getField:()=> 'Paper B original'};items.set(a.id,a);items.set(b.id,b);
 io.stats.set('/pdf/a.pdf',{size:1000,lastModified:1000});io.stats.set('/pdf/b.pdf',{size:2000,lastModified:2000});
 return{...io,c,s:new c.MinerUService(),a,b,imports,parseCalls,result,setParse:fn=>parseImpl=fn};
}
(async()=>{
 await check('Lifecycle: two rapid rebinds tolerate out-of-order stale callbacks',()=>{const f=serverFixture();f.s.start(23101);f.s.stop();f.s.start(23102);f.s.stop();f.s.start(23103);f.pending.reverse();f.flush();assert.equal(f.s.getBoundPort(),23103);f.s.stop();assert.ok(f.sockets.every(s=>s.closed));});
 await check('Lifecycle: stale accept closes transport without opening streams',async()=>{const f=serverFixture();f.s.start(23101);const old=f.s.serverSocket;f.s.stop();f.s.start(23102);let closed=0,opened=0;await f.s.listener.onSocketAccepted(old,{close(){closed++;},openInputStream(){opened++;throw Error('should not open');}});assert.equal(closed,1);assert.equal(opened,0);assert.equal(f.s.isServerRunning(),true);});
 await check('Lifecycle: unexpected active listener termination clears transports and MCP',()=>{const f=serverFixture();f.s.start(23101);let closed=0;f.s.activeTransports.add({close(){closed++;}});f.s.listener.onStopListening(f.s.serverSocket,123);assert.equal(f.s.isServerRunning(),false);assert.equal(f.s.serverSocket,null);assert.equal(closed,1);assert.equal(f.s.mcpServer,null);});
 await check('Lifecycle: stop closes actual listener even if running flag is false',()=>{const f=serverFixture();f.s.start(23101);const sock=f.s.serverSocket;f.s.isRunning=false;f.s.stop();assert.equal(sock.closed,true);});
 await check('Lifecycle: failed bind is cleaned up and next start can succeed',()=>{const f=serverFixture();f.fail(true);assert.throws(()=>f.s.start(23101),/bind failed/);assert.equal(f.s.serverSocket,null);assert.equal(f.sockets[0].closed,true);f.fail(false);f.s.start(23102);assert.equal(f.s.getBoundPort(),23102);});
 await check('Lifecycle: repeated stop and start while running are idempotent',()=>{const f=serverFixture();f.s.start(23101);f.s.start(23101);assert.equal(f.sockets.length,1);f.s.stop();f.s.stop();assert.equal(f.sockets[0].closeCalls,1);});
 await check('Lifecycle: one transport close failure does not block remaining cleanup',()=>{const f=serverFixture();f.s.start(23101);let closed=0;f.s.activeTransports.add({close(){throw Error('closed already');}});f.s.activeTransports.add({close(){closed++;}});f.s.stop();assert.equal(closed,1);assert.equal(f.s.activeTransports.size,0);assert.equal(f.sockets[0].closed,true);});

 await check('Reader: invalid cache owner is rejected',async()=>{const f=readerFixture();await assert.rejects(f.r.getAttachmentDataDir({key:'AAAABBBB',libraryID:0}),/libraryID/);});
 await check('Reader: isolated cache contents survive in-memory reset',async()=>{const f=readerFixture();for(const lib of [1,7]){const a={libraryID:lib,key:'SAMEKEY1'},ca=f.r.emptyTranslationCache(a,{sourceHash:'h'+lib});ca.glossary.manual=[{source:'word',target:'library'+lib}];await f.r.saveTranslationCache(a,ca);}f.r.state.translationCaches.clear();const ca=await f.r.loadTranslationCache({libraryID:7,key:'SAMEKEY1'},{sourceHash:'h7',blocks:[]});assert.equal(ca.glossary.manual[0].target,'library7');});
 await check('Reader: source change clears stale analysis but preserves manual glossary',async()=>{const f=readerFixture(),a={libraryID:1,key:'SOURCE01'};const ca=await f.r.loadTranslationCache(a,{sourceHash:'old',blocks:[]});ca.analyses.x={meaning:'old'};ca.glossary.manual=[{source:'x',target:'y'}];const cb=await f.r.loadTranslationCache(a,{sourceHash:'new',blocks:[]});assert.equal(cb,ca);assert.equal(cb.sourceHash,'new');assert.equal(Object.keys(cb.analyses).length,0);assert.equal(cb.glossary.manual[0].target,'y');});
 await check('Reader: explicit-owner legacy cache migrates to library-scoped path',async()=>{const f=readerFixture(),a={libraryID:7,key:'LEGACY01'},ca=f.r.emptyTranslationCache(a,{sourceHash:'hash'}),legacy='/test-data/zotero-lit-synapse/mineru/LEGACY01/translation-cache.json';ca.glossary.manual=[{source:'x',target:'migrated'}];f.disk.set(legacy,JSON.stringify(ca));const loaded=await f.r.loadTranslationCache(a,{sourceHash:'hash',blocks:[]});assert.equal(loaded.glossary.manual[0].target,'migrated');assert.ok(f.disk.has((await f.r.getAttachmentDataDir(a))+'/translation-cache.json'));assert.ok(f.disk.has(legacy));});
 await check('Reader: ownerless legacy cache migrates only with matching metadata and unique database owner',async()=>{const f=readerFixture(),a={libraryID:7,key:'LEGACY02'},ca=f.r.emptyTranslationCache(a,{sourceHash:'hash'}),dir='/test-data/zotero-lit-synapse/mineru/LEGACY02';delete ca.libraryID;ca.glossary.manual=[{source:'x',target:'safe'}];f.disk.set(dir+'/translation-cache.json',JSON.stringify(ca));f.disk.set(dir+'/meta.json',JSON.stringify({libraryID:7,attachmentKey:a.key}));f.setOwners([{itemID:7,libraryID:7}]);const loaded=await f.r.loadTranslationCache(a,{sourceHash:'hash',blocks:[]});assert.equal(loaded.glossary.manual[0].target,'safe');});
 await check('Reader: ambiguous legacy owner is not imported and original is untouched',async()=>{const f=readerFixture(),a={libraryID:7,key:'LEGACY03'},ca=f.r.emptyTranslationCache(a,{sourceHash:'hash'}),dir='/test-data/zotero-lit-synapse/mineru/LEGACY03';delete ca.libraryID;ca.glossary.manual=[{source:'x',target:'unsafe'}];const raw=JSON.stringify(ca);f.disk.set(dir+'/translation-cache.json',raw);f.disk.set(dir+'/meta.json',JSON.stringify({libraryID:7,attachmentKey:a.key}));f.setOwners([{itemID:1,libraryID:1},{itemID:7,libraryID:7}]);const loaded=await f.r.loadTranslationCache(a,{sourceHash:'hash',blocks:[]});assert.equal(loaded.glossary.manual.length,0);assert.equal(f.disk.get(dir+'/translation-cache.json'),raw);});
 await check('Reader: explicit wrong-library legacy cache is not imported',async()=>{const f=readerFixture(),a={libraryID:7,key:'LEGACY04'},ca=f.r.emptyTranslationCache({libraryID:1,key:a.key},{sourceHash:'hash'});ca.glossary.manual=[{source:'x',target:'wrong'}];f.disk.set('/test-data/zotero-lit-synapse/mineru/LEGACY04/translation-cache.json',JSON.stringify(ca));const loaded=await f.r.loadTranslationCache(a,{sourceHash:'hash',blocks:[]});assert.equal(loaded.glossary.manual.length,0);});
 await check('Reader: legacy cache with changed source is not imported',async()=>{const f=readerFixture(),a={libraryID:1,key:'LEGACY05'},ca=f.r.emptyTranslationCache(a,{sourceHash:'old'});ca.glossary.manual=[{source:'x',target:'old'}];f.disk.set('/test-data/zotero-lit-synapse/mineru/LEGACY05/translation-cache.json',JSON.stringify(ca));const loaded=await f.r.loadTranslationCache(a,{sourceHash:'new',blocks:[]});assert.equal(loaded.glossary.manual.length,0);});
 await check('Reader: invalid owner metadata in new cache is not trusted',async()=>{const f=readerFixture(),a={libraryID:7,key:'CURRENT1'},dir=await f.r.getAttachmentDataDir(a);const ca=f.r.emptyTranslationCache({libraryID:1,key:a.key},{sourceHash:'hash'});ca.glossary.manual=[{source:'x',target:'wrong'}];f.disk.set(dir+'/translation-cache.json',JSON.stringify(ca));const loaded=await f.r.loadTranslationCache(a,{sourceHash:'hash',blocks:[]});assert.equal(loaded.libraryID,7);assert.equal(loaded.glossary.manual.length,0);});
 await check('Reader: concurrent cross-library writes notify distinct identities and clear queues',async()=>{const f=readerFixture(),notified=[];f.r.state.cacheListeners.add(k=>notified.push(k));await Promise.all([1,7].map(lib=>{const a={libraryID:lib,key:'SAMEKEY1'};return f.r.saveTranslationCache(a,f.r.emptyTranslationCache(a,{sourceHash:'h'+lib}));}));assert.deepEqual(notified.sort(),['1:SAMEKEY1','7:SAMEKEY1']);assert.equal(f.r.state.translationCacheWrites.size,0);});
 await check('Reader: glossary editor updates only requested library-scoped document',async()=>{const f=readerFixture(),task=new f.t.FullTranslationTask([],{});task.documents=[1,7].map(lib=>{const attachment={libraryID:lib,key:'SAMEKEY1'};return{attachment,title:'Paper '+lib,cache:f.r.emptyTranslationCache(attachment,{sourceHash:'h'+lib}),savePromise:Promise.resolve()};});task.setDocumentGlossary('7:SAMEKEY1',[{source:'term',target:'library7'}]);await task.documents[1].savePromise;assert.equal(task.documents[0].cache.glossary.manual.length,0);assert.equal(task.documents[1].cache.glossary.manual[0].target,'library7');const snapshots=task.snapshot?task.snapshot():task.getSnapshot();assert.equal(snapshots.documents[1].attachmentIdentity,'7:SAMEKEY1');});

 await check('Index: incoming add and modify remain queued while build is busy',async()=>{const f=hookFixture();f.items.set(7,regular(7,'GROUP001',7));f.c.isAutoIndexing=true;await f.notify('add','item',[7],{});await f.notify('modify','item',[7],{});assert.equal(f.c.pendingAutoUpdateKeys.get('7:GROUP001'),true);await f.c.processPendingAutoUpdates();assert.equal(f.c.pendingAutoUpdateKeys.get('7:GROUP001'),true);assert.equal(f.builds.length,0);f.c.isAutoIndexing=false;await f.c.processPendingAutoUpdates();assert.equal(f.builds[0].libraryID,7);assert.equal(f.builds[0].force,true);assert.equal(f.c.pendingAutoUpdateKeys.size,0);});
 await check('Index: item arriving during an actual pending batch is drained after completion',async()=>{const f=hookFixture(),gate=deferred();f.items.set(7,regular(7,'GROUP002',7));let calls=0;f.service.buildIndex=async o=>{f.builds.push(o);if(++calls===1)await gate.promise;return{status:'completed',processed:0,total:0};};f.c.scheduleAutoUpdate('FIRST001',1,false);const run=f.c.processPendingAutoUpdates();await ticks();assert.equal(f.c.isAutoIndexing,true);await f.notify('add','item',[7],{});gate.resolve();await run;assert.equal(await f.runImmediate(),true);assert.deepEqual(f.builds.map(o=>o.libraryID),[1,7]);assert.equal(f.c.pendingAutoUpdateKeys.size,0);});
 await check('Index: group event during periodic personal-library build is drained afterwards',async()=>{const f=hookFixture(),gate=deferred();f.items.set(7,regular(7,'GROUP003',7));let calls=0;f.service.buildIndex=async o=>{f.builds.push(o);if(++calls===1)await gate.promise;return{status:'completed',processed:0,total:0};};await f.c.triggerAutoIndexBuild();assert.equal(f.c.isAutoIndexing,true);await f.notify('add','item',[7],{});gate.resolve();await ticks();assert.equal(await f.runImmediate(),true);assert.deepEqual(f.builds.map(o=>o.libraryID),[1,7]);assert.equal(f.c.pendingAutoUpdateKeys.size,0);});
 await check('Index: unavailable service preserves queue for retry',async()=>{const f=hookFixture();f.service.isReady=async()=>false;f.c.scheduleAutoUpdate('GROUP004',7,true);await f.c.processPendingAutoUpdates();assert.equal(f.c.pendingAutoUpdateKeys.get('7:GROUP004'),true);assert.equal(f.c.isAutoIndexing,false);assert.ok(f.c.autoUpdateRetryTimer);f.service.isReady=async()=>true;await f.c.processPendingAutoUpdates();assert.equal(f.builds[0].libraryID,7);assert.equal(f.c.pendingAutoUpdateKeys.size,0);});
 await check('Index: build busy result preserves exact forced request',async()=>{const f=hookFixture();f.service.buildIndex=async()=>({status:'busy'});f.c.scheduleAutoUpdate('GROUP005',7,true);await f.c.processPendingAutoUpdates();assert.equal(f.c.pendingAutoUpdateKeys.get('7:GROUP005'),true);assert.equal(f.c.isAutoIndexing,false);assert.ok(f.c.autoUpdateRetryTimer);});
 await check('Index: suspension stops queuing and drains; resume accepts later events',async()=>{const f=hookFixture();f.items.set(7,regular(7,'GROUP006',7));f.c.scheduleAutoUpdate('OLD00001',7,true);f.c.suspendSemanticAutoUpdates();await f.notify('add','item',[7],{});f.c.drainAutoUpdatesAfterBuild();assert.equal(f.c.pendingAutoUpdateKeys.size,0);f.c.resumeSemanticAutoUpdates();await f.notify('add','item',[7],{});assert.equal(f.c.pendingAutoUpdateKeys.get('7:GROUP006'),true);});
 await check('Index: disabled preference prevents new regular-item queuing',async()=>{const f=hookFixture();f.setEnabled(false);f.items.set(7,regular(7,'GROUP007',7));await f.notify('add','item',[7],{});assert.equal(f.c.pendingAutoUpdateKeys.size,0);});
 await check('Index: exhausted retries retain pending data instead of deleting it',async()=>{const f=hookFixture();f.c.isAutoIndexing=true;f.c.autoUpdateRetryCount=8;f.c.pendingAutoUpdateKeys.set('7:GROUP008',true);await f.c.processPendingAutoUpdates();assert.equal(f.c.pendingAutoUpdateKeys.get('7:GROUP008'),true);});

 await check('MinerU: ordinary forced parsing imports the matching result for one library',async()=>{const f=minerFixture();const text=await f.s.getMarkdownForAttachment(f.a,{force:true,allowParse:true,userInitiated:true});assert.match(text,/Paper A/);assert.equal(f.parseCalls.length,1);assert.equal(f.imports.length,1);assert.equal(f.imports[0].libraryID,1);return{parseCalls:f.parseCalls,importedLibrary:1};});
 await check('MinerU: same attachment duplicate requests correctly share one parse',async()=>{const f=minerFixture(),gate=deferred();f.setParse(async()=>{await gate.promise;return f.result('Paper A evidence.');});const p1=f.s.getMarkdownForAttachment(f.a,{force:true,allowParse:true,userInitiated:true});await ticks();const p2=f.s.getMarkdownForAttachment(f.a,{force:true,allowParse:true,userInitiated:true});await ticks();gate.resolve();const [r1,r2]=await Promise.all([p1,p2]);assert.equal(r1,r2);assert.equal(f.parseCalls.length,1);});
 await check('MinerU: different attachment keys do not share their parsing tasks',async()=>{const f=minerFixture(),gate=deferred();f.b.key='OTHERKEY';f.setParse(async p=>{if(p==='/pdf/a.pdf')await gate.promise;return f.result(p==='/pdf/a.pdf'?'Paper A evidence.':'Paper B evidence.');});const p1=f.s.getMarkdownForAttachment(f.a,{force:true,allowParse:true,userInitiated:true});await ticks();const p2=f.s.getMarkdownForAttachment(f.b,{force:true,allowParse:true,userInitiated:true});await ticks();gate.resolve();const [r1,r2]=await Promise.all([p1,p2]);assert.match(r1,/Paper A/);assert.match(r2,/Paper B/);assert.equal(f.parseCalls.length,2);assert.equal(f.imports.length,2);});
 await check('C1a confirmed: concurrent same-key PDFs from different libraries share the first parse result',async()=>{const f=minerFixture(),gate=deferred();f.setParse(async p=>{if(p==='/pdf/a.pdf')await gate.promise;return f.result(p==='/pdf/a.pdf'?'Paper A evidence.':'Paper B evidence.');});const p1=f.s.getMarkdownForAttachment(f.a,{force:true,allowParse:true,userInitiated:true});await ticks();const p2=f.s.getMarkdownForAttachment(f.b,{force:true,allowParse:true,userInitiated:true});await ticks();gate.resolve();const [r1,r2]=await Promise.all([p1,p2]);assert.match(r1,/Paper A/);assert.equal(r1,r2);assert.equal(f.parseCalls.length,1);assert.equal(f.imports.length,1);assert.equal(f.imports[0].libraryID,1);return{libraries:[1,7],sameAttachmentKey:f.a.key,differentFileStats:true,parseCalls:f.parseCalls,library7Received:r2,library7OwnPDFParsed:false};},true);
 await check('C1b confirmed: later library parse overwrites shared artifact path; freshness ignores cached library owner',async()=>{const f=minerFixture();await f.s.getMarkdownForAttachment(f.a,{force:true,allowParse:true,userInitiated:true});await f.s.getMarkdownForAttachment(f.b,{force:true,allowParse:true,userInitiated:true});const sameDir=f.s.getAttachmentDir(f.a.key);const meta=JSON.parse(f.disk.get(sameDir+'/meta.json'));assert.equal(meta.libraryID,7);f.stats.set('/pdf/a.pdf',{size:2000,lastModified:2000});const readA=await f.s.getMarkdownForAttachment(f.a,{allowParse:false});assert.match(readA,/Paper B/);assert.match(f.imports.at(-1).markdown,/Paper B/);assert.equal(f.imports.at(-1).libraryID,1);return{sharedArtifactDirectory:sameDir,cachedOwnerAfterB:meta.libraryID,statCollisionAddedForDiskReuse:true,library1ReadAfterB:readA,wrongMarkdownImportedToLibrary1:true};},true);
 const out=path.join(resultsRoot,'extended-results.json');fs.writeFileSync(out,JSON.stringify(checks,null,2));console.log(JSON.stringify(checks,null,2));if(checks.some(x=>x.status==='FAIL'))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
